version: "3"
services:
  postgres:
    build: 
      context: './postgres'
    restart: always
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=n8n
      - POSTGRES_NON_ROOT_USER=admin
      - POSTGRES_NON_ROOT_PASSWORD=password
  n8n:
    image: n8nio/n8n
    restart: always
    environment: 
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=admin
      - DB_POSTGRESDB_PASSWORD=password
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
    ports:
      - "${N8N_HTTP_PORT}:5678"
    links: 
      - postgres
    volumes:
      - "${APP_CODE_PATH_HOST}:/home/node/.n8n"
    # Wait 5 seconds to start n8n to make sure that PostgreSQL is ready
    # when n8n tries to connect to it
    command: /bin/sh -c "sleep 5; n8n start"
volumes: {}