version: "3"
services:
  mariadb:
    image: ghcr.io/deck-app/mariadb:${MARIADB_VERSION}
    restart: always
    environment: 
      - 'MARIADB_DATABASE=${DB_NAME}'
      - 'MARIADB_USER=${DB_USER}'
      - 'MARIADB_PASSWORD=${DB_PASSWORD}'
      - 'MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
      - 'MARIADB_MYSQL_LOCALHOST_USER=true'
    volumes:
      - ${DATA_PATH_HOST}:/var/lib/mysql
  n8n:
    image: n8nio/n8n
    restart: always
    environment: 
      - DB_TYPE=mariadb
      - DB_MYSQLDB_HOST=mariadb
      - DB_MYSQLDB_DATABASE=${DB_NAME}
      - DB_MYSQLDB_USER=${DB_USER}
      - DB_MYSQLDB_PASSWORD=${DB_PASSWORD}
      - N8N_BASIC_AUTH_ACTIVE=false
    ports:
      - "${N8N_HTTP_PORT}:5678"
    volumes:
      - "${APP_CODE_PATH_HOST}:/home/node/.n8n"
    # Wait 5 seconds to start n8n to make sure that PostgreSQL is ready
    # when n8n tries to connect to it
    command: /bin/sh -c "sleep 10; n8n start --tunnel"
volumes: {}