#User defined
user:
  # backend_ws:
  #   label:
  #     Backend webserver
  #   hint:
  #     Select a backend webserver
  #   type:
  #     select
  #   values:
  #     - apache
  #     - fpm
  #   target:
  #     MAUTIC_HTTP_SERVER

  # run_cron:
  #   label:
  #     Run cron jobs?
    # type:
    #   checkbox
    # hint:
    #   Check to enable cron jobs
    # target:
    #   MAUTIC_RUN_CRON
  MariaDB_version:
    label:
      MariaDB version
    hint:
      Select a MariaDB version from the list above
    type:
      select
    values:
      - "10.10"
      - 10.9
      - 10.7
    target:
      MARIADB_VERSION

#System defaults
system:
  show_localpath_selector:
    true
  #For collecting and storing DB in .env
  #db/user/password
  db_credentials:
    true
  #Generate public ports for the docker image
  ports:
    http: N8N_HTTP_PORT
